development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fiftydev
  username: iffydev
  password: secret
  template: template0
  pool: 5

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: fiftyprod
  username: iffyprod
  password: secret
  template: template0
  pool: 5
